//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookyourdoctor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Linq;
    using System.Data.Entity;



    public partial class doctor_scedule
    {
        [DataType(DataType.Time)]
        public System.DateTime clinic_time { get; set; }
        [DataType(DataType.Time)]
        public System.DateTime hospital_time { get; set; }
        [DataType(DataType.Time)]
        public System.DateTime clinic_end_time { get; set; }
        [DataType(DataType.Time)]
        public System.DateTime hospital_end_time { get; set; }
        public string is_avalible { get; set; }
        public string Clinic_day { get; set; }
        public string hospial_day { get; set; }
        public string doctor_id { get; set; }
        public static IEnumerable<SelectListItem> GetDay()
        {
            IList<SelectListItem> items = new List<SelectListItem>
        {

        new SelectListItem { Text="Monday",Value="Monday"},
        new SelectListItem { Text="Monday",Value="Monday"},
        };
            return items;
        }
   
            
           
    }
        
}
